// Generated by scripts/generate-catalog.mjs from species/*.json and src/assets/sprites.
// Do not edit by hand. Run `npm run generate` after adding or changing a pet.
(function () {
  const globalScope = typeof window !== 'undefined' ? window : self;
  if (globalScope.PettyCatalog) return;

  const species = {
    "bluebird": {"animations":[{"id":"front","position":"fromEntityBottomLeft"},{"id":"fly","position":"fromEntityBottomLeft"},{"id":"eat","position":"fromEntityBottomLeft","requiredLoops":2},{"id":"sing","position":"fromEntityBottomLeft","requiredLoops":2}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","BounceOnLateralCollisions","FlipHorizontallyWhenGoingLeft","LinearMovement","PetsSpritesProvider","Rotating","Flying","PerchesOnTrees"],"dragPath":"drag","fps":12,"zIndex":5,"tags":["birds"],"id":"bluebird","movementPath":"walk","speed":0.7,"flySpeed":3.2},
    "heron": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":1},{"id":"walk","position":"fromEntityBottomLeft","size":[2,2]},{"id":"fly","position":"fromEntityBottomLeft","size":[2,2]},{"id":"storm","position":"fromEntityBottomLeft","size":[2,2]},{"id":"drag","position":"fromEntityBottomLeft","size":[2,2]},{"id":"kungfu","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":1},{"id":"stance","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":3},{"id":"wade","position":"fromEntityBottomLeft","size":[2,2]},{"id":"strike","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":1},{"id":"catch","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":3},{"id":"gulp","position":"fromEntityBottomLeft","size":[2,2],"requiredLoops":1}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","BounceOnLateralCollisions","FlipHorizontallyWhenGoingLeft","LinearMovement","PetsSpritesProvider","Rotating","Flying","WadesInPonds","FliesInStorms"],"dragPath":"drag","fps":10,"zIndex":6,"tags":["birds","water"],"id":"heron","movementPath":"walk","speed":0.5,"flySpeed":2.6,"groundActions":["kungfu","stance","front"]},
    "kingfisher": {"animations":[{"id":"front","position":"fromEntityBottomLeft"},{"id":"fly","position":"fromEntityBottomLeft"},{"id":"fly_fish","position":"fromEntityBottomLeft"},{"id":"hover","position":"fromEntityBottomLeft","requiredLoops":4},{"id":"dive","position":"fromEntityBottomLeft"},{"id":"splash","position":"fromEntityBottomLeft","requiredLoops":1},{"id":"eat","position":"fromEntityBottomLeft","requiredLoops":1}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","BounceOnLateralCollisions","FlipHorizontallyWhenGoingLeft","LinearMovement","PetsSpritesProvider","Rotating","Flying","PerchesOnTrees","FishesInPonds"],"dragPath":"drag","fps":12,"zIndex":5,"tags":["birds","water"],"id":"kingfisher","movementPath":"walk","speed":0.6,"flySpeed":3.6},
    "pond": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[4.8,1.12]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","FishingSpot"],"dragPath":"front","fps":4,"zIndex":-110,"tags":["water","decorations"],"id":"pond","movementPath":"front","speed":0,"water":{"x":0.5,"y":0.78,"rx":0.37,"ry":0.17}},
    "pond_koi": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[4.4,1.44]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","FishingSpot"],"dragPath":"front","fps":4,"zIndex":-110,"tags":["water","decorations"],"id":"pond_koi","movementPath":"front","speed":0,"water":{"x":0.5,"y":0.833,"rx":0.355,"ry":0.132}},
    "pond_marsh": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[5.6,1.2]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","FishingSpot"],"dragPath":"front","fps":4,"zIndex":-110,"tags":["water","decorations"],"id":"pond_marsh","movementPath":"front","speed":0,"water":{"x":0.5,"y":0.8,"rx":0.375,"ry":0.167}},
    "pond_oasis": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[4.4,2.4]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","FishingSpot","PerchingPlace"],"dragPath":"front","fps":4,"zIndex":-110,"tags":["water","decorations"],"id":"pond_oasis","movementPath":"front","speed":0,"water":{"x":0.5,"y":0.9,"rx":0.318,"ry":0.075},"perches":[{"x":0.358,"y":0.263},{"x":0.485,"y":0.258}]},
    "robin": {"animations":[{"id":"front","position":"fromEntityBottomLeft"},{"id":"fly","position":"fromEntityBottomLeft"},{"id":"eat","position":"fromEntityBottomLeft","requiredLoops":2},{"id":"sing","position":"fromEntityBottomLeft","requiredLoops":2}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","BounceOnLateralCollisions","FlipHorizontallyWhenGoingLeft","LinearMovement","PetsSpritesProvider","Rotating","Flying","PerchesOnTrees"],"dragPath":"drag","fps":12,"zIndex":5,"tags":["birds"],"id":"robin","movementPath":"walk","speed":0.7,"flySpeed":3.2},
    "sparrow": {"animations":[{"id":"front","position":"fromEntityBottomLeft"},{"id":"fly","position":"fromEntityBottomLeft"},{"id":"eat","position":"fromEntityBottomLeft","requiredLoops":2},{"id":"sing","position":"fromEntityBottomLeft","requiredLoops":2}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","BounceOnLateralCollisions","FlipHorizontallyWhenGoingLeft","LinearMovement","PetsSpritesProvider","Rotating","Flying","PerchesOnTrees"],"dragPath":"drag","fps":12,"zIndex":5,"tags":["birds"],"id":"sparrow","movementPath":"walk","speed":0.7,"flySpeed":3.2},
    "tree_cherry": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[2,3]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","PerchingPlace"],"dragPath":"front","fps":1.5,"zIndex":-100,"tags":["plants","decorations"],"id":"tree_cherry","movementPath":"front","speed":0,"perches":[{"x":0.18,"y":0.607},{"x":0.84,"y":0.553},{"x":0.34,"y":0.1},{"x":0.5,"y":0.04},{"x":0.66,"y":0.08}]},
    "tree_oak": {"animations":[{"id":"front","position":"fromEntityBottomLeft","size":[2,3]}],"capabilities":["AnimatedSprite","AnimationsProvider","AutoRespawn","PetsSpritesProvider","PerchingPlace"],"dragPath":"front","fps":1.5,"zIndex":-100,"tags":["plants","decorations"],"id":"tree_oak","movementPath":"front","speed":0,"perches":[{"x":0.18,"y":0.607},{"x":0.84,"y":0.553},{"x":0.34,"y":0.1},{"x":0.5,"y":0.04},{"x":0.66,"y":0.08}]}
  };

  const frames = {
    "bluebird": {"drag":4,"eat":12,"fly":7,"front":30,"sing":12,"walk":6},
    "heron": {"catch":4,"drag":4,"fly":8,"front":50,"gulp":24,"kungfu":58,"stance":16,"storm":8,"strike":10,"wade":16,"walk":8},
    "kingfisher": {"dive":2,"drag":4,"eat":27,"fly":7,"fly_fish":7,"front":30,"hover":4,"splash":10,"walk":6},
    "pond": {"front":8},
    "pond_koi": {"front":8},
    "pond_marsh": {"front":8},
    "pond_oasis": {"front":8},
    "robin": {"drag":4,"eat":12,"fly":7,"front":30,"sing":12,"walk":6},
    "sparrow": {"drag":4,"eat":12,"fly":7,"front":30,"sing":12,"walk":6},
    "tree_cherry": {"front":4},
    "tree_oak": {"front":4}
  };

  globalScope.PettyCatalog = { species, frames };
  globalScope.SPECIES_LIST = Object.keys(species);
})();
