// Builds the source of src/shared/catalog.js from species/*.json and the sprite folder.
// The catalog lets the extension know every species and the exact frame count of every
// animation up front, so it never fetches JSON at runtime or probes for missing frames.

import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

export const ROOT = path.resolve(import.meta.dirname, '..', '..');
export const SPECIES_DIR = path.join(ROOT, 'species');
export const SPRITES_DIR = path.join(ROOT, 'src', 'assets', 'sprites');
export const CATALOG_FILE = path.join(ROOT, 'src', 'shared', 'catalog.js');

const FRAME_FILE = /^(.+)-(\d+)\.png$/;

/**
 * Reads every species definition, sorted by id.
 * @returns {Promise<Array<object>>}
 */
export async function readSpecies(speciesDir = SPECIES_DIR) {
  const files = (await readdir(speciesDir)).filter((f) => f.endsWith('.json')).sort();
  return Promise.all(
    files.map(async (file) => {
      const data = JSON.parse(await readFile(path.join(speciesDir, file), 'utf8'));
      const id = path.basename(file, '.json');
      if (data.id !== id) {
        throw new Error(`species/${file}: "id" is "${data.id}" but must match the file name "${id}"`);
      }
      return data;
    }),
  );
}

/**
 * Counts contiguous frames (0..n-1) per species and animation.
 * Sprite files are named `<speciesId>_<animationId>-<frame>.png`.
 * @returns {Promise<Record<string, Record<string, number>>>}
 */
export async function countFrames(speciesIds, spritesDir = SPRITES_DIR) {
  // Longest id first so "cat_black_walk" resolves to cat_black, not cat.
  const ids = [...speciesIds].sort((a, b) => b.length - a.length);
  const indexes = {};

  for (const file of await readdir(spritesDir)) {
    const match = FRAME_FILE.exec(file);
    if (!match) continue;
    const [, base, frame] = match;
    const id = ids.find((candidate) => base.startsWith(`${candidate}_`));
    if (!id) continue;
    const animation = base.slice(id.length + 1);
    ((indexes[id] ??= {})[animation] ??= new Set()).add(Number(frame));
  }

  const frames = {};
  for (const id of [...speciesIds].sort()) {
    frames[id] = {};
    for (const animation of Object.keys(indexes[id] ?? {}).sort()) {
      let count = 0;
      while (indexes[id][animation].has(count)) count++;
      if (count > 0) frames[id][animation] = count;
    }
  }
  return frames;
}

/**
 * @returns {Promise<string>} The full source text of src/shared/catalog.js.
 */
export async function generateCatalogSource({ speciesDir = SPECIES_DIR, spritesDir = SPRITES_DIR } = {}) {
  const species = await readSpecies(speciesDir);
  const frames = await countFrames(
    species.map((s) => s.id),
    spritesDir,
  );

  const speciesEntries = species.map((s) => `    ${JSON.stringify(s.id)}: ${JSON.stringify(s)}`).join(',\n');
  const frameEntries = Object.entries(frames)
    .map(([id, counts]) => `    ${JSON.stringify(id)}: ${JSON.stringify(counts)}`)
    .join(',\n');

  return `// Generated by scripts/generate-catalog.mjs from species/*.json and src/assets/sprites.
// Do not edit by hand. Run \`npm run generate\` after adding or changing a pet.
(function () {
  const globalScope = typeof window !== 'undefined' ? window : self;
  if (globalScope.PettyCatalog) return;

  const species = {
${speciesEntries}
  };

  const frames = {
${frameEntries}
  };

  globalScope.PettyCatalog = { species, frames };
  globalScope.SPECIES_LIST = Object.keys(species);
})();
`;
}
